In [3]:
import torch
import numpy as np
import torch.nn as nn

In [12]:
tensor = torch.tensor([[1,-2],[3,4]])
np.asarray(tensor,dtype=np.float32)

array([[ 1., -2.],
       [ 3.,  4.]], dtype=float32)

In [5]:
torch.tensor(np.array([[1,-2],[3,4]]))

tensor([[ 1, -2],
        [ 3,  4]])

In [6]:
torch.zeros([2,3],dtype=torch.float32)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [16]:
A = torch.randn([2,3,4])
print(A.shape)


torch.Size([2, 3, 4])


In [17]:
A

tensor([[[-1.4806,  0.5916,  0.2895, -1.0113],
         [-0.1285, -1.3721, -2.6720, -1.6660],
         [-2.6200,  2.2165, -0.3892, -1.3921]],

        [[-0.3536,  1.9962,  0.5611,  0.4613],
         [ 0.5959,  0.2545,  2.0291,  0.4400],
         [-0.2754, -0.8321, -1.3051, -1.2800]]])

In [ ]:
A_t = torch.transpose(A,0,2) # Pour  transpose un tenseur
A_t

tensor([[[-1.4806, -0.3536],
         [-0.1285,  0.5959],
         [-2.6200, -0.2754]],

        [[ 0.5916,  1.9962],
         [-1.3721,  0.2545],
         [ 2.2165, -0.8321]],

        [[ 0.2895,  0.5611],
         [-2.6720,  2.0291],
         [-0.3892, -1.3051]],

        [[-1.0113,  0.4613],
         [-1.6660,  0.4400],
         [-1.3921, -1.2800]]])

In [20]:
A1 = torch.randint(0,10 ,[4,4]) # tenseur de nombre entier entre 0 et 10 de dimention (4,4)
print(A1.shape)

torch.Size([4, 4])


In [ ]:
print(A1.view([2,8]))  # Reshape en numpy

tensor([[3, 6, 4, 0, 3, 0, 1, 2],
        [5, 6, 9, 3, 3, 0, 7, 9]])


In [ ]:
A1.flatten() # Applatir un tenseur (Mettre à plat)

tensor([3, 6, 4, 0, 3, 0, 1, 2, 5, 6, 9, 3, 3, 0, 7, 9])

In [ ]:
A = torch.randint([2,2] ,dtype=torch.float32)  # Change de type des elements de tenseur

In [8]:
# Creation de reseau de neuronne
from torch.nn import functional as F
class MyModel(nn.Module):
    '''
    Basic fully connected neural nets
    '''
    def __init__(self):
        hidden1 = 100  # premiere couche dense
        hidden2 = 100  # Deuxieme couche dense

        super(MyModel,self).__init__()
        self.hidden1 = nn.Linear(784,hidden1)
        self.hidden2 = nn.Linear(hidden1,hidden2)
        self.hidden3 = nn.Linear(hidden2,10)

    def forward(self,x):
        x = x.view(-1,784)
        x = self.hidden1(x)
        x = F.relu(x)
        x = self.hidden2(x)
        x = F.relu(x)
        x= self.hidden3(x)
        x = F.softmax(x,dim=0)
        return x


In [39]:
X  = torch.randn([5,2],requires_grad=False)  #  requires_grad=False => je ne veux pas calculer la grad de X
w = torch.randn([2],requires_grad=True)  #  requires_grad=True => je  veux  calculer la grad de X (car mon params à estimer)

y_pred = w[0]*X[:,0] + w[1]*X[:,1]
y_pred.retain_grad()

print('X :',X)
print('w :',w)
print('y_pred :',y_pred)

print('X.grad :',X.grad)
print('w.grad :',w.grad)
print('y_pred.grad :',y_pred.grad)

X : tensor([[-0.3695, -0.4510],
        [-0.7250,  1.8645],
        [ 0.4800, -0.3903],
        [ 0.4195, -0.7938],
        [-0.1379,  1.3580]])
w : tensor([0.1332, 0.1976], requires_grad=True)
y_pred : tensor([-0.1384,  0.2719, -0.0132, -0.1010,  0.2500], grad_fn=<AddBackward0>)
X.grad : None
w.grad : None
y_pred.grad : None


In [40]:
y_true = torch.zeros([5],requires_grad=False)
print('y_true :',y_true)


y_true : tensor([0., 0., 0., 0., 0.])


In [41]:
Risk = (torch.pow(y_pred - y_true,2)).mean()

In [42]:
Risk.backward()

In [43]:
print('X.grad :',X.grad)

X.grad : None


In [44]:
print('y_pred.grad :' ,y_pred.grad)

y_pred.grad : tensor([-0.0553,  0.1088, -0.0053, -0.0404,  0.1000])


In [45]:
print('w.grad :' ,w.grad)

w.grad : tensor([-0.0917,  0.3976])


In [47]:
x = torch.ones(10,requires_grad=True)
y = x**2
z = x**3
r = (y+z).sum()
r.backward()
print('X :' ,x)
print('y :' ,y)
print('z :',z)
print('r :',r)
print('x.grad :',x.grad)

X : tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], requires_grad=True)
y : tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], grad_fn=<PowBackward0>)
z : tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], grad_fn=<PowBackward0>)
r : tensor(20., grad_fn=<SumBackward0>)
x.grad : tensor([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])


In [ ]:
x = torch.ones(10 ,requires_grad=True)
y = x**2
z = x.detach()**3  # Version de x mais constante,requires_grad=False

r = (y+z).sum()
r.backward()

print(x.grad)

print('Z :',z)

tensor([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])
Z : tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])


In [ ]:
x = torch.ones(3,requires_grad=True)
y = x**2
z = x**3
r = (y + z).sum() # [1^2 + 1^3 ,1^2 + 1^3 ,1^2 + 1^3 ]
r.backward()


print('r :',r)
print('x.grad :',x.grad)

r : tensor(6., grad_fn=<SumBackward0>)
x.grad : tensor([5., 5., 5.])


In [55]:
x = torch.ones(3 ,requires_grad=True)

with torch.no_grad():
    y = x**2
    z = x**3
    r = (y + z).sum()

print('r :',r)
print('x.grad :',x.grad)

r : tensor(6.)
x.grad : None


In [57]:
print('Cuda disponible ',torch.cuda.is_available())
print("Nombre de divice ",torch.cuda.device_count())
# print('Divice utilisé ',torch.cuda.current_device())
# print("Nom de divice utilisé ",torch.cuda.get_device_name())

Cuda disponible  False
Nombre de divice  0


In [ ]:
import torchvision.models as models  # models sont des architecture de reseau de neurone

In [ ]:
DEVICE = torch.device('cude:0' if torch.cuda.is_available() else 'cpu') # DEVICE = "gpu" s'il existe ,sinon "cpu"
print(DEVICE)

h_resnet18 = models.resnet18() # h_resnet18 :host_de reseau de neuronne18
h_resnet18.fc = nn.Linear(512,5)

d_resnet18 = h_resnet18.to(DEVICE) # d_ :device , d_resnet18 = h_resnet18.cuda()

h_simulted_data = torch.randn([1000,3,64,64])
d_mini_batch = h_simulted_data[0:10,:,:,:].to(DEVICE) # Transfere sur le gpu s'il existe

d_outputs = d_resnet18(d_mini_batch)
h_outputs = d_outputs.to('cpu') # Transfere sur le cpu ,h_outputs = d_outputs.cpu()

print(h_outputs)

cpu
tensor([[ 0.1173, -0.2289, -0.2207, -0.3247, -0.6431],
        [-0.2962,  0.0048, -0.2195, -0.2730, -0.3446],
        [ 0.1804, -0.1870, -0.5170, -0.7864,  0.0123],
        [-0.1935, -0.1209, -0.0383, -0.3184, -0.5742],
        [-0.1815,  0.1029, -0.4725, -0.1713, -0.5394],
        [-0.1047,  0.8285,  0.0014, -0.5365, -0.3450],
        [-0.0050,  0.3172, -0.2243, -0.1803, -0.4370],
        [ 0.2733,  0.0315, -0.3158, -0.7414, -0.6371],
        [-0.2217, -0.1653, -0.0064, -0.4595, -0.6812],
        [-0.0499,  0.2070, -0.5706, -0.4306, -0.6979]],
       grad_fn=<AddmmBackward0>)


# 1) Etude d'un exemple

In [6]:
import torchvision

In [7]:
# Get and format the training set
mnist_trainset = torchvision.datasets.MNIST(root='./data',train=True ,download=True ,transform=None)
x_train = mnist_trainset.data.type(torch.DoubleTensor)
y_train = mnist_trainset.targets

# Get and format the test set
mnist_testset = torchvision.datasets.MNIST(root='./data' ,train=False ,download=True ,transform=None)
x_test = mnist_testset.data.type(torch.DoubleTensor)
y_test = mnist_testset.targets

100.0%
100.0%
100.0%
100.0%


In [ ]:
model = MyModel().to(DEVICE) # Mettre dans le carte GPU s'il exist

In [ ]:
# Fonction d'entrainement 
def fit(model,X_train,Y_train,X_test,Y_tetst,EPOCHS=5,BATCH_SIZE =32):
    loss = nn.CrossEntropyLoss()
    optimezer = torch.optim.Adam(model.parameters(),lr=1e-3)
    model.train()

    n = X_train.shape[0]

    #stochastic gradient descent
    for epoch in EPOCHS:
        batch_start = 0
        epoch_shuffler = np.arange(n)
        np.random.shuffle(epoch_shuffler)

        while batch_start + BATCH_SIZE < n:
            # Get mini_batch observation
            mini_batch_observation = epoch_shuffler[batch_start : batch_start+BATCH_SIZE]
            var_X_batch = X_train[mini_batch_observation,:,:].float().to(DEVICE)
            var_Y_batch = Y_train[mini_batch_observation]

            #Gradient descent step
            optimezer.zero_grad()
            Y_pred_batch = model(var_X_batch)
            curr_loss = loss(Y_pred_batch.to('cpu'),var_Y_batch)
            curr_loss.backward()
            optimezer.step()

            # Prepare the next mini_batch of epoch
            batch_start += BATCH_SIZE